name: "Clone URL Shortener Github Actions"

on:
  push:
    schedule:
      - cron: "*/30 * * * *" 
jobs:
  deploy-url-shortener:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout limistah:url-shortner"
        uses: actions/checkout@v1
        with:
          repository: "limistah/url-shortner"
          ref: "master"
      - name: "Create .netrc for Heroku Auth"
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}
          heroku_app_name: "aleem-urls-via-github-actions"
          heroku_email: "gatobumalex@gmail.com"
        working-directory: /home/runner/work/aleem-urls/url-shortner
      - name: "Add remote"
        shell: bash
        run: |
          cd ../url-shortner && heroku git:remote -a aleem-urls-via-github-actions
      - name: "Push to heroku"
        shell: bash
        run: |
          cd ../url-shortner && git push heroku HEAD:refs/heads/master