name: "Clone URL Shortener Github Actions"

on:
  push:
    schedule:
      - cron: "*/30 * * * *" 
jobs:
  deploy-url-shortener:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout limistah:url-shortner"
        uses: actions/checkout@v2
        with:
          path: "./url-shortner"
          repository: "limistah/url-shortner"
          ref: "master"
      - name: "Check app"
        shell: bash
        run: |
          echo "Parent directory"
          cd .. && ls -al
          echo "Infra directory"
          cd aleem-urls && ls -al
          echo "App directory"
          ls -al url-shortner
      - name: "Create .netrc for Heroku Auth"
        shell: bash
        run: |
          `cat > ~/.netrc <<EOF
          machine api.heroku.com
            login $EMAIL
            password $HEROKU_AUTH_TOKEN
          machine git.heroku.com
            login $EMAIL
            password $HEROKU_AUTH_TOKEN
          EOF`
        env:
          EMAIL: gatobumalex@gmail.com 
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      - name: "Add remote"
        working-directory: url-shortner
        shell: bash
        run: |
          heroku git:remote -a aleem-urls-via-github-actions
      - name: "Push to heroku"
        working-directory: url-shortner
        shell: bash
        run: |
          git push heroku HEAD:refs/heads/master