name: "Clone URL Shortener Github Actions"

on:
  push:
    schedule:
      - cron: "*/30 * * * *" 
jobs:
  deploy-url-shortener:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout alex-magana:aleem-urls"
        uses: actions/checkout@v2
        with:
          repository: "alex-magana/aleem-urls"
          ref: "main"
      - name: "Checkout limistah:url-shortner"
        uses: actions/checkout@v2
        with:
          path: "./url-shortner"
          repository: "limistah/url-shortner"
          ref: "master"
      - name: "Check app"
        shell: bash
        run: |
          echo "Parent directory"
          cd .. && ls -al
          echo "Infra directory"
          cd aleem-urls && ls -al
          echo "App directory"
          ls -al url-shortner
      - name: "Create .netrc for Heroku Auth"
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}
          heroku_app_name: "aleem-urls-via-github-actions"
          heroku_email: "gatobumalex@gmail.com"
          appdir: "url-shortner"
      - name: "Add remote"
        shell: bash
        run: |
          cd ../url-shortner && heroku git:remote -a aleem-urls-via-github-actions
      - name: "Push to heroku"
        shell: bash
        run: |
          cd ../url-shortner && git push heroku HEAD:refs/heads/master